server:
  port: 8070

jwt:
  secret: 49c8b2a8b5b27adee4d0596714bd8792a92b2ac81cbb175141bc82d9ca2b3065

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
