server:
  port: 8070

jwt:
  secret: cc29adf4e7f1f44ce6593487a7d4fc3a710e158fe6def24e8bfc629e4f349250

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
